apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-dashboard-frontend
  template:
    metadata:
      labels:
        app: metrics-dashboard-frontend
    spec:
      containers:
      - name: metrics-dashboard-frontend
        image: patralekha/metrics-dashboard-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: metrics-dashboard-frontend
  ports:
    - port: 77
      targetPort: 7777
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitoring
  namespace: monitoring
  labels:
    app: metrics-dashboard-frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: metrics-dashboard-frontend
  endpoints:
  - port: frontend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
