apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitoring
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
  namespace: monitoring
  labels:
    app: metrics-dashboard-frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: metrics-dashboard-frontend
  endpoints:
  - port: frontend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
