apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-dashboard-frontend
  template:
    metadata:
      labels:
        app: metrics-dashboard-frontend
    spec:
      containers:
      - name: metrics-dashboard-frontend
        image: patralekha/metrics-dashboard-frontend:v1
        imagePullPolicy: Always
        ports:
        - name: frontenddepport
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: metrics-dashboard-frontend
  ports:
    - name: frontend
      port: 9090
      targetPort: frontenddepport
  type: LoadBalancer


