apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metrics-dashboard-frontend
  template:
    metadata:
      labels:
        app: metrics-dashboard-frontend
    spec:
      containers:
      - name: metrics-dashboard-frontend
        image: patralekha/metrics-dashboard-frontend:v1
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: metrics-dashboard-frontend
  ports:
    - port: 7777
      targetPort: 7777
  type: LoadBalancer