apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-backend
  annotations:
    "sidecar.jaegertracing.io/inject": "true" 
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    name: metrics-dashboard-backend
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-dashboard-backend
  template:
    metadata:
      labels:
        app: metrics-dashboard-backend
    spec:
      containers:
      - name: metrics-dashboard-backend
        image: patralekha/metrics-dashboard-backend:v1
        imagePullPolicy: Always
        ports:
        - name: backenddepport
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: metrics-dashboard-backend
  ports:
    - name: backend
      port: 90
      targetPort: backenddepport
  type: LoadBalancer

