apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-backend
  annotations:
    "sidecar.jaegertracing.io/inject": "true" 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metrics-dashboard-backend
  template:
    metadata:
      labels:
        app: metrics-dashboard-backend
    spec:
      containers:
      - name: metrics-dashboard-backend
        image: patralekha/metrics-dashboard-backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: metrics-dashboard-backend
  ports:
    - port: 90
      targetPort: 9090
  type: LoadBalancer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitoring
  namespace: monitoring
  labels:
    app: metrics-dashboard-backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: metrics-dashboard-backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
