apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitoring
  annotations: 
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backend
  namespace: monitoring
  labels:
    app: metrics-dashboard-backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: metrics-dashboard-backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
