apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: patralekha/trial:v1
        magePullPolicy: Always
        ports:
        - name: trial-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
spec:
  selector:
    app: trial
  ports:
    - port: 8083
      targetPort: trial-port
  type: LoadBalancer
